# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: KellyLford.QuickMail
PackageVersion: 0.8.53
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
RequireExplicitUpgrade: true
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: QuickMail
  Publisher: Kelly Ford
  ProductCode: MSI:QuickMail
  InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kellylford/QuickMail/releases/download/v0.8.53/QuickMail-0.8.53-win.msi
  InstallerSha256: 729C7E6945E5DB296BF322EB30CB8098DE34BF2A1D2342D3DF310039EFB3890B
- Architecture: arm64
  InstallerUrl: https://github.com/kellylford/QuickMail/releases/download/v0.8.53/QuickMail-0.8.53-win-arm64.msi
  InstallerSha256: 8306EB141A1DB2208C0BF7A3488883B62B038D579DDDB7F189B06AA2904BBE15
ManifestType: installer
ManifestVersion: 1.12.0
